// sensorType 传感器类型
export const SET_ALL_SENSORTYPE = 'SET_ALL_SENSORTYPE'
export const SET_SENSORTYPE = 'SET_SENSORTYPE'

// deviceType 设备类型
export const SET_ALL_DEVICETYPE = 'SET_ALL_DEVICETYPE'
export const SET_DEVICETYPE = 'SET_DEVICETYPE'

// 场景类型
export const SET_ALL_AREATYPE = 'SET_ALL_AREATYPE'
export const SET_AREATYPE = 'SET_AREATYPE'

// 验证
export const VALID_TRUE = 'VALID_TRUE'
export const VALID_FALSE = 'VALID_FALSE'

export const CHANGE_TOKEN_TRUE = 'CHANGE_TOKEN_TRUE'
export const CHANGE_TOKEN_FALSE = 'CHANGE_TOKEN_FALSE'
export const GET_USER_INFO = 'GET_USER_INFO'


export const GET_PROJECT_TYPE = 'GET_PROJECT_TYPE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
export const GET_CAPTCHAURL = 'GET_CAPTCHAURL'
export const RESET_VUEX = 'RESET_VUEX'

export const GET_PEOPLE = 'GET_PEOPLE'
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_USER_PROJECT = 'GET_USER_PROJECT'

export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS'
export const VERIFICATION_FALSE = 'VERIFICATION_FALSE'

export const CHANGE_DEL_ID = 'CHANGE_DEL_ID'
export const CHANGE_DEL_TYPE = 'CHANGE_DEL_TYPE'
export const GET_SENSORTYPES = 'GET_SENSORTYPES'

export const PROJECT_IN = 'PROJECT_IN'
export const PROJECT_OUT = 'PROJECT_OUT'

export const MODEL_SHOW_TRUE = 'MODEL_SHOW_TRUE'
export const MODEL_SHOW_FALSE = 'MODEL_SHOW_FALSE'

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const CHANGE_STYLE_MODE = 'CHANGE_STYLE_MODE'
export const GET_INDEX_IMG = 'GET_INDEX_IMG'

export const SUCCESS_GET_SNSLOGINS = 'SUCCESS_GET_SNSLOGINS'
export const FAILURE_GET_SNSLOGINS = 'FAILURE_GET_SNSLOGINS'

export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS'
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE'
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'

export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const PRENEXT_ARTICLE = 'PRENEXT_ARTICLE'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'

export const COMMENT_LIST = 'COMMENT_LIST'
export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT'
export const SUCCESS_ADD_REPLY = 'SUCCESS_ADD_REPLY'
export const GET_COMMENT_LIST_FAILURE = 'GET_COMMENT_LIST_FAILURE'
export const SUCCESS_GET_APPS = 'SUCCESS_GET_APPS'
export const FAILURE_GET_APPS = 'FAILURE_GET_APPS'


